// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://linfqkihuyyyflindoit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbmZxa2lodXl5eWZsaW5kb2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjMwNTEsImV4cCI6MjA2NDkzOTA1MX0.2sO61Bp6kiCveed6Y0aykglVZxdhQqLdMzHs8Jtgizs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);